### ISSUE TITLE
Use Specific SDRs

### ISSUE THREAD

**Issue by BT-Justice** [DSheirer/sdrtrunk#1087] opened 2021-10-03 21:40 UTC
Is there a way to tell sdrtrunk to only use specific SDRs when opened and ignore all other SDRs hooked up to a computer?  I use 2 RTL-SDR.com V3 SDRs to monitor a trunked system.  These are actually really good SDRs.  I want to use a couple of other ones in other software for other needs like dump1090 and shortwave listening.  I know I can open other software and use the other SDRs which makes them unavailable in sdrtrunk, but I am looking for a more permanent way to tell sdrtrunk specifically which two SDRs I want it to use.

I did this to give them different serial numbers:

https://forum.radarbox24.com/index.php?topic=19831.msg268761#msg268761

**Comment by kkomarica** [comment] 2022-01-03 15:00
I also have a similar problem and I would also like to use only a certain SDR with SDRTrunk. 
That would be a great feature to have!

**Comment by hans109h** [comment] 2022-01-03 15:08
Duplicate of known feature enhancement: https://github.com/DSheirer/sdrtrunk/issues/119

**Comment by DSheirer** [comment] 2022-04-24 10:27
This feature was added and will be in the next (0.5.0 beta 3) release.

**Closed by DSheirer** 2022-04-24 10:27 UTC
