### ISSUE TITLE
Java with with RTLSDRv3

### ISSUE THREAD

**Issue by bigalnz** [DSheirer/sdrtrunk#1290] opened 2022-07-22 14:10 UTC
Hi Danny,

Just wondering if I can use your Lib to write a high level (read easy) program to count the pulses per minute on a VHF CW freq?

Cheers

Al

**Comment by DSheirer** [comment] 2022-07-23 08:27
Sure, that's possible.  The channelizers generally provide a 25-50 kHz channel, but if you need wider bandwidth, you could create a custom implementation.

Most components extend the Module abstract class and the ProcessingChain is a framework for coordinating the modules in a demod chain.

**Comment by DSheirer** [comment] 2022-07-23 12:35
Closing.  This is not a bug or feature request.

Usage questions can be posted here: https://groups.google.com/g/sdrtrunk

**Closed by DSheirer** 2022-07-23 12:35 UTC
