### ISSUE TITLE
SDRTrunk Broadcasting feed

### ISSUE THREAD

**Issue by hccr717** [DSheirer/sdrtrunk#1527] opened 2023-04-18 20:46 UTC
So i am trying to provide a audio feed to broacasting and when i set it up and enable it all it what to do is connect and disconnect non stop please help me. Im new at this stuff

**Comment by reppiZ** [comment] 2023-04-20 15:20
What broadcasting service are you trying to use? Icecast, Broadcastify?

**Comment by hccr717** [comment] 2023-04-21 17:31
Broadcastify

**Comment by hccr717** [comment] 2023-05-01 23:08
guest no one knows

**Comment by DSheirer** [comment] 2023-05-02 09:47
If it's trying to connect, failing and then disconnecting, then it sounds like you might have some sort of networking issue.  The software is trying to connect to the broadcastify server and failing.

There may be an error listed in the application log.  Can you post here and attach the application log?

**Comment by hccr717** [comment] 2023-05-02 15:28
what logs do i need to look at? new at this

**Comment by reppiz** [comment] 2023-05-02 15:43
You doing this over Wi-Fi or Ethernet? I used to use Broadcastify before making my own icecast server and never had any issues with using them. Definitely sounds like a network problem and less of a problem
With SDRTrunk.

**Comment by hccr717** [comment] 2023-05-02 18:32
how do u do it over icecast

**Comment by reppiz** [comment] 2023-05-02 18:39
You need to have the icecast server running on a machine, then you put in the IP, mount point, and password of the icecast server into the fields on SDRTrunk.

**Comment by hccr717** [comment] 2023-05-02 18:40
ok how

**Comment by reppiz** [comment] 2023-05-02 18:55
Little too complicated to write it out here. I'd be happy to help via a voice chat over Discord or something similar. Or you can try to Google it yourself.

**Comment by DSheirer** [comment] 2023-05-07 11:32
Closing.  This appears to be more of a user-help request and not a bug/anomaly with sdrtrunk clode.

**Closed by DSheirer** 2023-05-07 11:32 UTC
