### ISSUE TITLE
Regarding designing of 4-FSK using siglib

### ISSUE THREAD

**Issue by JasleenKaur2308** [DSheirer/sdrtrunk#1804] opened 2024-01-23 10:45 UTC
I am successfully able to get the results for 2-FSK  using siglib as designed in the link below.
Link - https://github.com/Numerix-DSP/siglib/blob/main/Examples/CExamples/fsk.c

I wanted to design for 4-FSK using the siglib in the same way , how should i designed it and what all changes are required to get the results for 4-FSK using Siglib .

**Comment by DSheirer** [comment] 2024-01-23 11:30
I don't understand how this applies to sdrtrunk?

**Comment by DSheirer** [comment] 2024-01-23 21:39
Closing.  If this is indeed an sdrtrunk issue, then please reopen and clarify what the issue is.

**Closed by DSheirer** 2024-01-23 21:39 UTC
