### ISSUE TITLE
Output demodulated sound to the network

### ISSUE THREAD

**Issue by ah1102** [DSheirer/sdrtrunk#738] opened 2020-04-10 13:07 UTC
I apologize. But is it possible to somehow bring sound to the network? My computer is in the room, and I would like to be in the kitchen listening to conversations, for example, using a phone or tablet connected to my home network. Let's say open the address in a browser (localhost: 8000 or 127.0.0.1:8000).

I tried to play in broadcast mode, but nothing worked. Broadcasts are somehow connected with the need to connect to the server.

I need to send sound to a local home network without a server. How to do it?

**Comment by DSheirer** [comment] 2020-04-10 13:25
Please post user questions like this to the google group help forum at: https://groups.google.com/forum/#!forum/sdrtrunk

Or, you can post them on the discord user support channel: https://discord.gg/HJQaKYE

To answer your question:

There's currently no way to stream audio directly from sdrtrunk to a streaming client.

The easiest way is to setup your own local Icecast server on a computer.  This can be the same computer where you're running sdrtrunk.

Update the sdrtrunk playlist to add a broadcast configuration and update your aliases to stream to that broadcast configuration.

Then you can use any streaming audio application on your phone or tablet to connect to the local icecast server.

I'm closing this issue since it's not a bug report.

**Closed by DSheirer** 2020-04-10 13:25 UTC

**Comment by ah1102** [comment] 2020-04-10 13:29
thanks
