### ISSUE TITLE
Add table column width persistence

### ISSUE THREAD

**Issue by DSheirer** [DSheirer/sdrtrunk#107] opened 2017-01-13 20:07 UTC
Add capability to save current state of table column widths so that the column settings are persisted between application runs.

Add persistence to all JTables in the application.

**Comment by sdrtrunkuser** [comment] 2017-03-24 10:16
Accidentally created a dupe of this, but this feature would be much appreciated! +1

**Closed** 2019-01-27 12:09 UTC
Labels: enhancement, low
