### ISSUE TITLE
OutOfMemoryError exception thrown when audio is muted

### ISSUE THREAD

**Issue by grumble1965** [DSheirer/sdrtrunk#137] opened 2017-01-25 18:23 UTC
When I leave the audio muted for a period of time, the application eventually fails with an out of memory exception.  This doesn't happen if I leave the audio playing.  I'd guess there's a code path when muted where a sample isn't being collected.

Running V0.3.0--alpha1 (with latest commits) on windows 10 with an Airspy.

> Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "D3D Screen Updater"
> Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "sdrtrunk pool-1-thread-2"
> Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "sdrtrunk pool-1-thread-1"
> Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "AWT-EventQueue-0"
> Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Airspy Buffer Processor"

**Comment by DSheirer** [comment] 2017-01-26 01:16
This issue is probably the same as #126 and it is likely caused by the airspy tuner filling an unbounded buffer with samples (at 10 MHz) while java stops the consumer thread during an extended garbage collection phase.  This is the next bug in the hopper to fix and I hope to have it resolved by this weekend.

The audio output(s) continuously write samples to the mixer and rely on the mixer itselft to either mute the channel or not.  So, there shouldn't be any path switching that depends on the mute setting.

**Comment by DSheirer** [comment] 2017-01-28 14:11
I just committed the fix for #126.  I'm going to close this issue.  Please let me know if you are still seeing issues with this out of memory error.

**Closed by DSheirer** 2017-01-28 14:11 UTC

**Comment by grumble1965** [comment] 2017-01-30 16:48
Just built the latest commits - works like a champ!  Thanks for the help!
