### ISSUE TITLE
SDRPlay API 3.12:  /usr/local/lib/libsdrplay_api.dylib  shm_open: No such file or directory

### ISSUE THREAD

**Issue by winstonsf** [DSheirer/sdrtrunk#1644] opened 2023-08-29 04:12 UTC
**sdrtrunk Version**
sdr-trunk-osx-aarch64-v0.6.0-alpha7

**Describe the bug**
Unable to open /libsdrplay_api.dylib

**To Reproduce**
1. Run ./sdr-trunk from /bin or double click icon from bin folder
2. See error
i.g.d.s.t.s.api.SDRplay - Loading API Library from default install path: /usr/local/lib/libsdrplay_api.dylib  [12MB/256MB 4%]
shm_open: No such file or directory

**Expected behavior**
SDRplay API 3.12 should be loaded and RSPduo tuner should be found

**Application Log**
2023-08-28 20:57:40.398 INFO  i.g.d.icon.IconModel - loading icons file [/var/root/SDRTrunk/settings/icons.xml]  [14MB/256MB 5%]
2023-08-28 20:57:40.400 INFO  i.g.d.icon.IconModel - Icons file not found at [/var/root/SDRTrunk/settings/icons.xml]  [14MB/256MB 5%]
2023-08-28 20:57:40.582 INFO  i.g.d.log.ApplicationLog - Application Log File: /var/root/SDRTrunk/logs/sdrtrunk_app.log  [21MB/256MB 8%]
2023-08-28 20:57:40.604 INFO  i.g.d.log.ApplicationLog - SDRTrunk Version  : 0.6.0-alpha7  [6MB/256MB 2%]
2023-08-28 20:57:40.604 INFO  i.g.d.log.ApplicationLog - Gradle Version    : Gradle 8.2  [6MB/256MB 2%]
2023-08-28 20:57:40.604 INFO  i.g.d.log.ApplicationLog - Build Timestamp   : 2023-07-14T07:14:49.022-0400  [6MB/256MB 2%]
2023-08-28 20:57:40.604 INFO  i.g.d.log.ApplicationLog - Build-JDK         : 20.0.1 (BellSoft 20.0.1+10  [6MB/256MB 2%]
2023-08-28 20:57:40.604 INFO  i.g.d.log.ApplicationLog - Build OS          : Linux (amd64 5.19.0-46-generic  [6MB/256MB 2%]
2023-08-28 20:57:40.604 INFO  i.g.d.log.ApplicationLog -   [6MB/256MB 2%]
2023-08-28 20:57:40.604 INFO  i.g.d.log.ApplicationLog - *******************************************************************  [6MB/256MB 2%]
2023-08-28 20:57:40.605 INFO  i.g.d.log.ApplicationLog - **** sdrtrunk: a trunked radio and digital decoding application ***  [6MB/256MB 2%]
2023-08-28 20:57:40.605 INFO  i.g.d.log.ApplicationLog - ****  website: https://github.com/dsheirer/sdrtrunk             ***  [6MB/256MB 2%]
2023-08-28 20:57:40.605 INFO  i.g.d.log.ApplicationLog - *******************************************************************  [6MB/256MB 2%]
2023-08-28 20:57:40.605 INFO  i.g.d.log.ApplicationLog - Memory Logging Format: [Used/Allocated PercentUsed%]  [6MB/256MB 2%]
2023-08-28 20:57:40.605 INFO  i.g.d.log.ApplicationLog - Host OS Name:          Mac OS X  [6MB/256MB 2%]
2023-08-28 20:57:40.605 INFO  i.g.d.log.ApplicationLog - Host OS Arch:          aarch64  [7MB/256MB 2%]
2023-08-28 20:57:40.605 INFO  i.g.d.log.ApplicationLog - Host OS Version:       14.0  [7MB/256MB 2%]
2023-08-28 20:57:40.605 INFO  i.g.d.log.ApplicationLog - Host CPU Cores:        10  [7MB/256MB 2%]
2023-08-28 20:57:40.605 INFO  i.g.d.log.ApplicationLog - Host Max Java Memory:  4 GB  [7MB/256MB 2%]
2023-08-28 20:57:40.605 INFO  i.g.d.log.ApplicationLog - Storage Directories:  [7MB/256MB 2%]
2023-08-28 20:57:40.605 INFO  i.g.d.log.ApplicationLog -  Application Root: /var/root/SDRTrunk  [7MB/256MB 2%]
2023-08-28 20:57:40.606 INFO  i.g.d.log.ApplicationLog -  Application Log:  /var/root/SDRTrunk/logs  [7MB/256MB 2%]
2023-08-28 20:57:40.606 INFO  i.g.d.log.ApplicationLog -  Event Log:        /var/root/SDRTrunk/event_logs  [7MB/256MB 2%]
2023-08-28 20:57:40.606 INFO  i.g.d.log.ApplicationLog -  Playlist:         /var/root/SDRTrunk/playlist  [7MB/256MB 2%]
2023-08-28 20:57:40.606 INFO  i.g.d.log.ApplicationLog -  Recordings:       /var/root/SDRTrunk/recordings  [7MB/256MB 2%]
2023-08-28 20:57:40.647 INFO  i.g.d.util.ThreadPool - Application thread pool created SCHEDULED and CACHED executors threads  [10MB/256MB 4%]
2023-08-28 20:57:40.648 INFO  i.g.dsheirer.gui.SDRTrunk - Home path: /var/root/SDRTrunk  [10MB/256MB 4%]
2023-08-28 20:57:40.648 INFO  i.g.d.p.SystemProperties - SystemProperties - loaded [/var/root/SDRTrunk/SDRTrunk.properties]  [10MB/256MB 4%]
2023-08-28 20:57:40.648 INFO  i.g.d.p.SystemProperties - SystemProperties - application properties loaded [/var/root/SDRTrunk/SDRTrunk.properties]  [10MB/256MB 4%]
2023-08-28 20:57:40.655 INFO  i.g.d.s.t.m.TunerManager - Discovering tuners ...  [11MB/256MB 4%]
2023-08-28 20:57:40.872 INFO  i.g.d.s.t.m.TunerManager - LibUsb API Version: 1.0.264  [11MB/256MB 4%]
2023-08-28 20:57:40.873 INFO  i.g.d.s.t.m.TunerManager - LibUsb Version: 1.0.24.11584  [11MB/256MB 4%]
2023-08-28 20:57:40.878 INFO  i.g.d.s.t.m.TunerManager - LibUsb - discovered [5] potential usb devices  [11MB/256MB 4%]
2023-08-28 20:57:40.880 INFO  i.g.d.s.t.m.TunerManager - LibUsb - starting HotPlug detection  [11MB/256MB 4%]
2023-08-28 20:57:40.894 INFO  i.g.d.s.t.s.api.SDRplay - Loading API Library from default install path: /usr/local/lib/libsdrplay_api.dylib  [12MB/256MB 4%]
shm_open: No such file or directory
2023-08-28 20:57:40.928 INFO  i.g.d.s.t.s.api.SDRplay - API library - open status: Fail  [9MB/34MB 28%]
2023-08-28 20:57:40.928 ERROR i.g.d.s.t.m.TunerManager - Couldn't load SDRPlay API  [10MB/34MB 30%]
2023-08-28 20:57:40.930 INFO  i.g.d.s.SettingsManager - SettingsManager - loading settings file [/var/root/SDRTrunk/settings/settings.xml]  [10MB/34MB 30%]
2023-08-28 20:57:41.108 WARN  i.g.d.v.VectorUtilities - CPU supports maximum SIMD instructions of Species[float, 4, S_128_BIT]  [16MB/38MB 43%]

**Desktop (optional - complete the following information):**
 - OS: Sonoma 14.0 beta 23A5328b
 - CPU Cores: M2 Pro
 - RAM: 16GB

**Comment by DSheirer** [comment] 2023-08-29 07:40
Can you post a listing or screenshot of the contents of this directory:

/usr/local/lib/

**Comment by DSheirer** [comment] 2023-08-29 07:45
> This does exist in my system: usr/local/lib/libsdrplay_api.dylib

I misread this at first ... did you have an older (<3.12) version of the API installed and create this file as a symbolic link, or is this the first time that you're using sdrtrunk with sdrplay on this computer?  If you previously created a symbolic link, and then updated to API 3.12, the symbolic link may be pointing to the wrong filename.

**Comment by DSheirer** [comment] 2023-08-31 10:59
@winstonsf Can you tell me what are the file permissions on fiel:  **/usr/local/lib/libsdrplay_api.dylib**?

**Comment by DSheirer** [comment] 2023-09-01 08:40
Could you please do a ```ls -l libsdrplay*``` to show what the symbolic link(s) are pointing to?

On my Linux machine, my API 3.07 files displays as:

```
lrwxrwxrwx 1 root root     34 Sep 17  2021 libsdrplay_api.so -> /usr/local/lib/libsdrplay_api.so.3
lrwxrwxrwx 1 root root     37 Sep 17  2021 libsdrplay_api.so.3 -> /usr/local/lib/libsdrplay_api.so.3.07
-rw-r--r-- 1 root root  56176 Sep 17  2021 libsdrplay_api.so.3.07
```

**Comment by wx-jc** [comment] 2023-09-23 05:40
Any updates on this issue?  I ran into this same issue (new install).  When running SoapySDRUtil --probe, no devices show up, but the RSDduo works fine with the SDRPlay software.   

Version 3.12.0 of the API is the only option they have on the website for MacOS.  Couldn't find an older version to try.

**Comment by DSheirer** [comment] 2023-11-05 12:23
I updated sdrtrunk to recognize API version 3.12 as a compatible version, however this likely doesn't address the issue that Java cannot find or access the actual library binary on OSX systems.  More troubleshooting is required to identify the cause or solution.

**Comment by wx-jc** [comment] 2023-11-08 03:59
Still receiving this error with 0.6.0-beta-4.  Do I need to reload anything for the SDRPlay API?

**Comment by DSheirer** [comment] 2023-11-08 07:53
I contacted the SDRPlay team yesterday and they are aware that there is an issue with the SDRPlay API version 3.12 for the Mac.  The below email details several commands you need to execute on the command line to correct the installation.  Can you please try running each of the commands they recommended and then try again with SDRTrunk to see if this resolves the issue?

-------------------------------------
Hello Dennis,
There are a couple of issues with the 3.12 install which we will address in the next release.
This is known to work once 3.12 is installed…
```
sudo mkdir -p /usr/local/lib
sudo ln -s /Library/SDRplayAPI/3.12.0/lib/libsdrplay_api.3.12.0 /usr/local/lib/libsdrplay_api.so.3.12
sudo ln -s /usr/local/lib/libsdrplay_api.so.3.12 /usr/local/lib/libsdrplay_api_arm64.so.3.12
sudo ln -s /usr/local/lib/libsdrplay_api.so.3.12 /usr/local/lib/libsdrplay_api_x64.so.3.12
sudo ln -s /usr/local/lib/libsdrplay_api.so.3.12 /usr/local/lib/libsdrplay_api.so.3
sudo ln -s /usr/local/lib/libsdrplay_api.so.3 /usr/local/lib/libsdrplay_api.so
sudo ln -s /usr/local/lib/libsdrplay_api.so /usr/local/lib/libsdrplay_api.dylib
``` 

Best regards,
Andy

**Comment by wx-jc** [comment] 2023-11-09 02:43
Still not working for me.  Curious to see if it works for anyone else.

**Comment by DSheirer** [comment] 2023-11-18 08:37
@wx-jc Some additional comments/actions from the SDRPlay team:

```
Hi Denny, I wanted to do a bit of follow up on this. I followed the instructions sent by Any on my Intel Mac mini with success, here’s a couple of screenshots:
...
I then tried the same approach on my M1 Mac mini with not so good results! I spoke to Andy and he suggested the following additional commands:

sudo cp /Applications/SDRconnect.app/Content/MacOS/libusb-1.0.0.dylib /usr/local/lib/

(Note this requires SDRconnect to be installed first!)

On my machine the service did not start for some reason, so the following was added:

sudo launchctl load -w /Library/LaunchDaemons/com.sdrplay.service.plist
sudo launchctl enable system/com.sdrplay.service
sudo launchctl start system/com.sdrplay.service

You can check the service is running by doing this:

sudo launchctl list | grep -I sdr

After a reboot the service should run ok without further intervention.

All this aggravation will go away when Andy updates the API installer, but he’s (busy) with SDRconnect right now. But I’m sure he will publish something in a couple of weeks. Until then this is the best we can do. It works too!

```

**Comment by wx-jc** [comment] 2023-11-22 05:19
Hi Denny.  This temporary workaround that you posted works!  Thanks for sharing.

**Comment by DSheirer** [comment] 2023-12-01 09:01
Updated instructions added to the wiki for the Mac SDRPlay API version 3.12 here: https://github.com/DSheirer/sdrtrunk/wiki/FAQ

Closing issue.

**Closed by DSheirer** 2023-12-01 09:01 UTC
Labels: bug
